# Generated by Django 4.2.7 on 2023-11-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interjection',
            name='conversation_type',
            field=models.CharField(choices=[('T', 'Translate'), ('E', 'Edit'), ('C', 'Chat')], default='T', max_length=1),
        ),
    ]
